backend:
  name: git-gateway
  branch: master

# publish_mode: editorial_workflow

media_folder: "static/img/upload"
public_folder: "/img/upload"

# https://www.netlifycms.org/docs/add-to-your-site/#collections
# https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Date", name: "publishdate", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Builder", name: "builder", widget: "list", default: ["Aurélien SUCHET Architecte"]}
      - {label: "Period", name: "period", widget: "string"}
      - {label: "Surface", name: "surface", widget: "string"}
      - {label: "Cost", name: "cost", widget: "string"}
      - {label: "Images Legacy", name: "imagesLegacy", widget: "list", field: {label: Image, name: image, widget: image}}
      - label: "Images"
        name: "images"
        widget: "list"
        collapsed: false
        summary: '{{field.name}} - {{field.label}}'
        field:
          - label: Image
             name: image
             widget: image
      - {label: "Body", name: "body", widget: "markdown"}
